// WHO (Identity - People)
const who_phrases = [
  "Who are you?",
  "Who is this?",
  "Who told you that?",
  "Who was that?",
  "Who's that guy?",
  "Who's that girl?",
  "Who are those people?",
  "Who's your friend?",
  "Who isn't coming?",
  "Who doesn't know about this?",
  "Who else is coming?",
  "Who's in charge here?",
  "Who's up next?",
  "Who's on the phone?",
  "Who's asking?",
  "Who's coming with you?",
  "Who's picking you up?"
];

// WHAT (Information - Things)
const what_phrases = [
  "What's this?",
  "What's that?",
  "What're you doing?",
  "What do you mean?",
  "What's wrong?",
  "What happened?",
  "What do you think?",
  "What's going on?",
  "What's up?",
  "What's the matter?",
  "What's the deal with the printer?",
  "What's the deal with all the traffic today?",
  "What's the deal with Sarah?",
  "What's the deal with that new company policy?",
  "What's the deal with the meeting being moved to 7 a.m.?",
  "What for?",
  "What's it like?",
  "What don't you understand?",
  "What didn't you do?",
  "What brings you here?",
  "What made you decide that?",
  "What are you looking for?",
  "What are you talking about?",
  "What are you getting at?",
  "What's your point?",
  "What's the catch?",
  "What's taking so long?",
  "What's next?",
  "What's your plan?"
];

// WHERE (Location - Direction)
const where_phrases = [
  "Where is the nearest coffee shop?",
  "Where is John's office?",
  "Where is the meeting room?",
  "Where is your car parked?",
  "Where is the bathroom?",
  "Where are you?",
  "Where are you going?",
  "Where you going?",
  "Where're you headed?",
  "Where do you live?",
  "Where were you?",
  "Where'd you go?",
  "Where aren't you allowed?",
  "Where have you been?",
  "Where should we meet?",
  "Where does this go?",
  "Where do I sign?"
];

// WHEN (Time)
const when_phrases = [
  "When is the deadline?",
  "When is your birthday?",
  "When is the next train?",
  "When is the party starting?",
  "When is she coming back?",
  "When's the party?",
  "When are you coming?",
  "When did you arrive?",
  "When'd you arrive?",
  "When'll you be ready?",
  "When do you start?",
  "What time is it?",
  "What time do we leave?",
  "When can't you make it?",
  "When's good for you?",
  "When does it end?",
  "When was the last time you saw him?",
  "When was the last time you ate?",
  "When was the last time you went on vacation?",
  "When was the last time you talked to her?",
  "When was the last time you had a day off?"
];

// WHY (Reason - Cause)
const why_phrases = [
  "Why can't we meet tomorrow?",
  "Why are you late?",
  "Why'd you do that?",
  "Why do you ask?",
  "Why's that?",
  "Why don't you try calling him?",
  "Why don't you take a break?",
  "Why don't you ask for help?",
  "Why don't you come with us?",
  "Why don't you tell her how you feel?",
  "How come?",
  "Why aren't you ready?",
  "Why don't you try it?",
  "Why didn't you tell me?",
  "Why can't you come?",
  "Why bother?",
  "Why the rush?",
  "Why so serious?"
];

// HOW (Manner - Process)
const how_phrases = [
  "How are you?",
  "How're you doing?",
  "How's it going?",
  "How do you make this work?",
  "How do you get there?",
  "How do you spell your name?",
  "How do you deal with stress?",
  "How do you turn this on?",
  "How do you say 'thank you' in Portuguese?",
  "How do you say that in English?",
  "How do you say this word?",
  "How do you say 'goodbye' formally?",
  "How do you say 'excuse me' in Japanese?",
  "How does this work?",
  "How was your day?",
  "How you feeling?",
  "How do I get there?",
  "How should I do this?",
  "How can I help?",
  "How's that possible?",
  "How did that happen?",
  "How much is too much?",
  "How far is it?"
];

// WHICH (Selection - Choice)
const which_phrases = [
  "Which one do you want?",
  "Which one's better?",
  "Which do you prefer?",
  "Which one's yours?",
  "Which way should I go?",
  "Which one don't you like?",
  "You wouldn't prefer this one?",
  "Which one did you pick?",
  "Which reminds me, I still owe you a reply.",
  "Which reminds me, have you heard from her yet?",
  "Which reminds me, I need to pick up some milk later.",
  "Which reminds me, we should probably book that hotel soon.",
  "Which reminds me, I wanted to ask you something."
];

// HOW MUCH - HOW MANY (Quantity)
const how_much_many_phrases = [
  "How much is it?",
  "How much is this?",
  "How much water do you drink?",
  "How many do you have?",
  "How many brothers and sisters do you have?",
  "How many times?",
  "How much time do you need?",
  "How long does it take?",
  "How long will it take?",
  "You don't have enough?",
  "How many didn't you finish?",
  "How much longer?",
  "How come there's so many?"
];

// WHOSE (Possession)
const whose_phrases = [
  "Whose is this?",
  "Whose phone is this?",
  "Whose idea was that?",
  "Whose turn is it?",
  "Whose side are you on?"
];

// Present Perfect Questions (Have - Has + past participle)
const present_perfect_questions_phrases = [
  "Have you ever been to Italy?",
  "Have you ever tried sushi?",
  "Have you ever seen that movie?",
  "Have you ever thought about it?",
  "Have you ever had food poisoning?",
  "Have you finished yet?",
  "Have you heard from him?",
  "Have you decided yet?",
  "Have you eaten anything today?",
  "Have you spoken to her?",
  "Has it stopped raining?",
  "Has anyone called?",
  "Has he left already?",
  "Has she replied yet?",
  "Has anything changed?",
  "How long have you been waiting?",
  "How long have you lived here?",
  "How long have you been doing this?",
  "How long has she been gone?",
  "How long have you known each other?",
  "How many times have you been there?",
  "Haven't you done this before?",
  "Haven't you heard?",
  "Haven't we met before?",
  "Haven't you finished yet?",
  "Has it ever crossed your mind?",
  "Have you ever regretted a decision?",
  "Have you already started?",
  "Have you given it any thought?",
  "Have they arrived yet?"
];

// Future Questions (Will - Going to)
const future_questions_phrases = [
  "Will you be there?",
  "Will it take long?",
  "Will they let us in?",
  "Will you call me later?",
  "Will it be ready by tomorrow?",
  "Won't you be tired?",
  "Won't that be too late?",
  "Won't it be cold?",
  "Won't they notice?",
  "Won't she be upset?",
  "Are you going to be okay?",
  "Is it going to rain?",
  "What are you going to do about it?",
  "Where are you going to stay?",
  "How are you going to get there?",
  "Who's going to tell him?",
  "When are you going to be done?",
  "What will happen if we don't?",
  "How will you know?",
  "How long will you be gone?"
];

// Past Continuous Questions (Was - Were + -ing)
const past_continuous_questions_phrases = [
  "What were you doing when I called?",
  "Were you sleeping?",
  "Were you listening?",
  "Was he working when you arrived?",
  "What was she saying?",
  "Were you expecting someone?",
  "Was it raining when you left?",
  "Were they arguing again?",
  "What were you thinking?",
  "Were you paying attention?",
  "Was anyone watching?",
  "Were you waiting long?"
];

// Past Perfect Questions (Had + past participle)
const past_perfect_questions_phrases = [
  "Had you met him before?",
  "Had you already eaten?",
  "Had they left by the time you got there?",
  "Had she ever mentioned it before?",
  "Had you finished before he arrived?",
  "Had you already heard the news?",
  "Had anyone warned you?",
  "Had you been there before?",
  "Had he already gone when you called?",
  "Had you ever seen anything like that?"
];

// Future Plans (Going to)
const future_plans_phrases = [
  "You gonna go out?",
  "Are you going to the gym later?",
  "Are you going to tell him?",
  "Are you going to finish that?",
  "Are you going to apply for the job?",
  "Are you going to call her back?",
  "Are you going to eat now?",
  "You'll be there, right?",
  "You planning to stay long?",
  "You planning to move out?",
  "You planning to quit your job?",
  "You planning to travel this year?",
  "You planning to buy a new car?"
];

// Invitations and Proposals (Want - Would like)
const invitations_proposals_phrases = [
  "Wanna go?",
  "You wanna grab lunch?",
  "You wanna watch a movie?",
  "You wanna come over?",
  "You wanna try this?",
  "You wanna talk about it?",
  "Do you want to join us?",
  "Do you want to leave now?",
  "Do you want to order pizza?",
  "Do you want to reschedule?",
  "Do you want to sit down?",
  "Would you like to come to dinner?",
  "Would you like to see the menu?",
  "Would you like to try a sample?",
  "Would you like to take a seat?",
  "Would you like to hear more?",
  "You're not going?",
  "You won't be there?",
  "You don't wanna come?",
  "Wouldn't you like to join us?"
];

// Ability and Achievement (Manage - Able - Make it)
const ability_achievement_phrases = [
  "Did you manage to fix the issue?",
  "Did you manage to talk to the boss?",
  "Did you manage to finish the report?",
  "Did you manage to find your keys?",
  "Did you manage to book the tickets?",
  "Did you manage to fix it?",
  "Were you able to find it?",
  "Did you make it?",
  "Did you make it on time?",
  "Did you get the ticket?",
  "You get it done?",
  "How'd you manage to do that?",
  "You didn't manage to call them back?",
  "You didn't manage to complete the task?",
  "You didn't manage to send the email?",
  "You didn't manage to make it to the meeting?",
  "You didn't manage to fix the printer?",
  "You weren't able to reach him?",
  "You weren't able to log in?",
  "You weren't able to get time off?",
  "You weren't able to find parking?",
  "You weren't able to finish on time?",
  "You didn't make it?"
];

// Past Experience (Did - Were)
const past_experience_phrases = [
  "Did you like it?",
  "You sleep well?",
  "Did you finish?",
  "Were you home?",
  "What'd you do today?",
  "Where'd you go?",
  "You didn't like it?",
  "Didn't you finish?",
  "You weren't there?",
  "Weren't you at home?",
  "Did you hear about the news?",
  "Did you hear about what happened?",
  "Did you hear about the accident on the highway?",
  "Did you hear about the new restaurant downtown?",
  "Did you hear about Mark getting promoted?",
  "Did you see that?"
];

// Habits and Routines (Usually - Normally)
const habits_routines_phrases = [
  "Do you work here?",
  "You study English?",
  "Do you usually work from home?",
  "Do you usually take the train?",
  "Do you usually eat breakfast?",
  "Do you usually go to bed late?",
  "Do you usually exercise in the morning?",
  "Do you usually wake up early?",
  "What time do you usually have lunch?",
  "What time do you usually finish work?",
  "What time do you usually go to sleep?",
  "What time do you usually leave the house?",
  "What time do you usually wake up?",
  "Don't you like coffee?",
  "Don't you think it's cold?",
  "Don't you want to come?",
  "Don't you remember me?",
  "Don't you agree?",
  "You don't work here?",
  "Don't you usually drive to work?",
  "Don't you usually check your email first?",
  "Don't you usually have a meeting on Mondays?",
  "Don't you usually leave earlier than this?",
  "Don't you usually bring your own lunch?",
  "You never told me that!",
  "You never eat vegetables?",
  "You never watch TV?",
  "You never called me back.",
  "You never go out on weekends?",
  "How often do you go to the gym?",
  "How often do you see your family?",
  "How often do you check social media?",
  "How often do you travel?",
  "How often do you cook at home?",
  "Do you ever feel overwhelmed?",
  "Do you ever think about moving abroad?",
  "Do you ever regret it?",
  "Do you ever just want to give up?",
  "Do you ever miss your hometown?"
];

// Current Activity (Progressive)
const current_activity_phrases = [
  "You working?",
  "Are you busy right now?",
  "He sleeping?",
  "What're you up to?",
  "What are you up to?",
  "You're not working?",
  "Aren't you busy?",
  "He's not sleeping?",
  "What you up to?"
];

// Opinion and Assessment (Think - Feel - About)
const opinion_assessment_phrases = [
  "What do you think about the new project?",
  "What do you think about working remotely?",
  "What do you think about moving to London?",
  "What do you think about her idea?",
  "What do you think about this design?",
  "How do you feel about the decision?",
  "How do you feel about trying something new?",
  "How do you feel about the changes?",
  "How do you feel about going back to school?",
  "How do you feel about the weather today?",
  "Do you like living here?",
  "Do you like your job?",
  "Do you like spicy food?",
  "Do you like the new design?",
  "Do you like working with him?",
  "You agree?",
  "What's your take on this situation?",
  "What's your take on remote work?",
  "What's your take on the new policy?",
  "What's your take on electric cars?",
  "What's your take on the whole thing?",
  "How do you see it?",
  "You don't like it?",
  "Don't you agree?",
  "Wouldn't you say that it's too expensive?",
  "Wouldn't you say that he was right?",
  "Wouldn't you say that we need more time?",
  "Wouldn't you say that things are improving?",
  "Wouldn't you say that she deserves a second chance?"
];

// Reaction and Confirmation
const reaction_confirmation_phrases = [
  "Really?",
  "And then what?",
  "How was it?",
  "What about you?",
  "You do that a lot?",
  "Would you do it again?",
  "You didn't?",
  "You haven't?",
  "Tell me more.",
  "For real?",
  "No way!",
  "Seriously?",
  "Are you serious?",
  "I can't believe it",
  "That's crazy"
];

// Requests and Help (Can - Could)
const requests_help_phrases = [
  "Can you help me with this?",
  "Can you pass me the salt?",
  "Can you believe it?",
  "Can you hear me?",
  "Can you drive?",
  "Can you help me?",
  "Can I ask you something?",
  "Could you show me how?",
  "Could you send me the file?",
  "Could you speak up a bit?",
  "Could you hold this for me?",
  "Could you give me a ride?",
  "Could you repeat that?",
  "Want me to help?",
  "You want some help?",
  "Can't you help?",
  "Couldn't you have called earlier?",
  "Couldn't you just email them?",
  "Couldn't you wait a bit longer?",
  "Couldn't you find someone else to do it?",
  "Couldn't you have told me sooner?",
  "Would you be able to send me that file?",
  "Would you be able to help me tomorrow?",
  "Would you be able to pick me up?",
  "Would you be able to cover my shift?",
  "Would you be able to stay a bit later?"
];

// Permission (Mind - Okay - May)
const permission_phrases = [
  "Do you mind if I open the window?",
  "Do you mind if I sit here?",
  "Do you mind if I ask you something?",
  "Do you mind if I leave early?",
  "Do you mind if I borrow this for a minute?",
  "You mind if I turn on the light?",
  "You mind if I smoke here?",
  "You mind if I tag along?",
  "You mind if I use your phone?",
  "You mind if I take a look?",
  "Is it okay if I sit here?",
  "Is it okay if I leave early today?",
  "Is it okay if I bring a friend?",
  "Is it okay if I call you later?",
  "Is it okay if I pay you back next week?",
  "Would it be alright if I borrowed this?",
  "Would it be alright if I rescheduled?",
  "Would it be alright if I took tomorrow off?",
  "Would it be alright if I brought my dog?",
  "Would it be alright if I parked here?",
  "May I come in?",
  "May I ask you a question?",
  "May I use your restroom?",
  "May I speak with the manager?",
  "May I have a moment of your time?"
];

// Clarification (Repeat - Spell - Mean)
const clarification_phrases = [
  "Sorry, can you say that again?",
  "Sorry, what?",
  "Can you say that again?",
  "Could you speak slower?",
  "What does 'procrastinate' mean?",
  "What does that sign mean?",
  "What does it mean when she says that?",
  "What does this symbol mean?",
  "What does 'deadline' mean exactly?",
  "What's 'ASAP' mean?",
  "What's that word mean?",
  "What's this button mean?",
  "What's 'ghosting' mean?",
  "What's that expression mean?",
  "How do you spell that?",
  "Sorry, I didn't catch that.",
  "One more time?",
  "Come again?",
  "Huh?",
  "What?",
  "You don't understand?",
  "Can't you hear me?"
];

// Hypothetical (Would - If - What if)
const hypothetical_phrases = [
  "If I had more time, I'd travel the world.",
  "If I spoke fluent English, I'd apply for that job.",
  "If I were you, I wouldn't worry about it.",
  "If I were in your shoes, I'd take the offer.",
  "If I were in your position, I'd think twice.",
  "If I had the chance, I'd do it differently.",
  "If I could start over, I'd choose a different career.",
  "If I could go back in time, I'd study harder.",
  "If I could change one thing, it would be that.",
  "If money weren't an issue, I'd quit tomorrow.",
  "If it were up to me, I'd cancel the whole thing.",
  "If it were my call, I'd go with option B.",
  "If I didn't have to work, I'd spend more time with my family.",
  "If I lived closer, I'd visit more often.",
  "If I knew the answer, I'd tell you.",
  "If I had a car, I wouldn't take the bus every day.",

  "If I were you, I'd talk to her about it.",
  "If I were you, I'd get a second opinion.",
  "If I were you, I'd sleep on it.",
  "If I were you, I'd let it go.",
  "If I were you, I wouldn't take it personally.",
  "If I were you, I'd keep my options open.",
  "If I were you, I'd set some boundaries.",
  "If I were in your place, I'd ask for a raise.",
  "What would you do if you were in my situation?",
  "What would you do differently if you could?",

  "If you were here, what would you do?",
  "What would you do if you were me?",
  "Where would you go if you could?",
  "If you had the money, would you buy it?",
  "What would you do if you won the lottery?",
  "What would you do if you lost your job?",
  "What would you do if you saw someone in trouble?",
  "What would you do if she said no?",
  "What would you do if you could live anywhere?",
  "Would you move abroad if you got the chance?",
  "Would you take the job if they offered it?",
  "Would you forgive him if he apologised?",
  "Would you still love me if I were poor?",
  "Would you say yes if they asked you?",
  "Would it matter if we changed the deadline?",
  "Would it make a difference if I apologised?",
  "Would you mind if I tagged along?",
  "How would you feel if someone did that to you?",
  "How would you handle it if your boss said no?",
  "How would you react if you found out the truth?",
  "Where would you go if you could live anywhere?",
  "Who would you call if you were in trouble?",

  "If I had known, I would have told you.",
  "If I had known earlier, I would have done something.",
  "If you had told me, I would have helped.",
  "If we had left earlier, we would have made it on time.",
  "If she had asked, I would have said yes.",
  "If I had studied harder, I would have passed.",
  "If they had listened, none of this would have happened.",
  "If I hadn't been so stubborn, things would have been different.",
  "If I hadn't moved here, I never would have met you.",
  "If we hadn't taken that risk, we wouldn't be here today.",
  "If he had been honest from the start, we could have avoided all this.",
  "If I had paid more attention, I would have noticed.",
  "If you had warned me, I wouldn't have gone.",
  "If it hadn't rained, we would have gone to the beach.",
  "Things would have been different if we had planned ahead.",
  "I wouldn't have said that if I had known how you felt.",
  "None of this would have happened if you had just listened.",

  "What if you were wrong?",
  "What if we're late?",
  "What if it rains?",
  "What if he doesn't show up?",
  "What if this doesn't work?",
  "What if I fail?",
  "What if we just skip it?",
  "What if they find out?",
  "What if something goes wrong?",
  "What if it's too late?",
  "What if we can't afford it?",
  "What if nobody comes?",
  "What if she changes her mind?",
  "What if the plan falls through?",
  "What if we get caught?",
  "What if I told you there's another way?",
  "What if we tried a different approach?",
  "What if we just said no?",
  "What if that's not the real problem?",
  "What if we're overthinking this?",
  "What if we're looking at this the wrong way?",

  "Let's suppose that you get the job, then what?",
  "Let's suppose that we have unlimited budget.",
  "Let's suppose that she agrees to help.",
  "Let's suppose that everything goes wrong.",
  "Let's suppose that they say no, what's plan B?",
  "Suppose you had to choose, which one would you pick?",
  "Suppose we don't get the funding, what then?",
  "Suppose they reject the proposal, what's our backup?",
  "Suppose it doesn't go as planned.",
  "Suppose we flip it around and try the opposite.",
  "Let's say you get the promotion. What's your first move?",
  "Let's say we have two weeks. Is that enough?",
  "Let's say they agree. What happens next?",
  "Let's say the worst happens. Can we recover?",
  "Let's say we start from scratch. How would we do it?",
  "Let's say, hypothetically, that money is no object.",
  "Just say, for argument's sake, that they refuse.",
  "Imagine you wake up tomorrow and it's all sorted.",
  "Imagine you could have any job in the world.",
  "Imagine we had unlimited resources.",
  "Imagine if everyone thought like that.",
  "Picture this: you're the boss. What do you change first?",
  "Say you had one shot at this. Would you take it?",

  "Even if I had the money, I wouldn't buy it.",
  "Even if they asked nicely, I'd still say no.",
  "Even if it were free, I wouldn't go.",
  "Even if you're right, it doesn't matter.",
  "Even if we tried, it wouldn't make a difference.",
  "Even if I wanted to, I couldn't.",
  "I wouldn't do it even if you paid me.",
  "I'd support you even if everyone else disagreed.",

  "He acts as if he owned the place.",
  "She talks as if she knew everything.",
  "They treat me as if I were invisible.",
  "He looked at me as though I were crazy.",
  "It felt as if nothing had changed.",
  "It's not as if we have a choice.",
  "It's not as if I asked for this.",
  "Don't act as if nothing happened.",

  "I wish I had more time.",
  "I wish I could help.",
  "I wish I knew what to say.",
  "I wish it were that simple.",
  "I wish I were better at this.",
  "I wish things were different.",
  "I wish I hadn't said that.",
  "I wish I had listened to you.",
  "I wish we had met sooner.",
  "I wish I could take it back.",
  "If only I had known.",
  "If only we had more time.",
  "If only things were different.",
  "If only I could turn back the clock.",
  "If only I had been there.",
  "If only someone had told me.",

  "I'd rather not talk about it.",
  "I'd rather stay in tonight.",
  "I'd rather you didn't mention it.",
  "I'd rather we kept this between us.",
  "I'd rather not get involved, if I'm honest.",
  "Would you rather work from home or go to the office?",
  "Would you rather play it safe or take the risk?",

  "It's time we made a decision.",
  "It's time we had a serious conversation.",
  "It's time you told him the truth.",
  "It's about time we did something about it.",
  "It's high time we moved on.",

  "I should have known better.",
  "I should have seen it coming.",
  "I should have said something.",
  "You should have told me sooner.",
  "We should have thought of that.",
  "I could have handled it better.",
  "It could have been worse.",
  "It could have gone either way.",
  "That could have been a disaster.",
  "We could have avoided this.",
  "It might have worked if we'd tried harder.",
  "Things might have turned out differently.",
  "She might have said yes if you'd asked.",

  "If I can do that, I'll do this.",
  "If I can't do that, I won't do this.",
  "Hypothetically speaking, what would you do?",
  "Just out of curiosity, what would you choose?",
  "In theory, that should work, but in practice...",
  "In an ideal world, we'd have more time.",
  "In a perfect world, everyone would agree.",
  "If worst comes to worst, we'll figure it out.",
  "If push comes to shove, I'll do it myself.",
  "If all else fails, we start over.",
  "If need be, I can stay late.",
  "If it came down to it, would you do it?",
  "If it were that easy, everyone would do it.",
  "If only it were that simple.",
  "That's easier said than done.",
  "On the off chance that it works, we'd save a fortune.",
  "There's a slim chance it could work, but I doubt it.",
  "Best-case scenario, we finish by Friday.",
  "Worst-case scenario, we lose a week.",
  "Say the word and I'll make it happen.",

  "We need to leave now, otherwise we'll be late.",
  "You'd better hurry, or else we'll miss it.",
  "I'd keep quiet if I were you, otherwise it'll get worse.",
  "We should save some money, otherwise we'll run out.",

  "Unless something changes, I'm not going.",
  "Unless you ask, you'll never know.",
  "Unless we act now, it'll be too late.",
  "I won't go unless you come with me.",
  "We can't move forward unless everyone agrees.",
  "Unless I'm mistaken, that's not what we agreed on.",

  "As long as we stick to the plan, we'll be fine.",
  "As long as you're happy, that's all that matters.",
  "Provided that everything goes smoothly, we'll finish on time.",
  "Provided that they agree, we can move forward.",
  "I'm fine with it as long as it doesn't affect the deadline.",
  "I don't mind, as long as you let me know in advance."
];

// Tag Questions (Confirmation)
const tag_questions_phrases = [
  "It's hot, isn't it?",
  "You're coming, aren't you?",
  "She didn't call, did she?",
  "You can help, can't you?",
  "That was fun, wasn't it?",
  "You don't mind, do you?",
  "You've been there before, haven't you?"
];

// Conversation Starters and Small Talk Openers
const conversation_starters_phrases = [
  "Can you believe this weather?",
  "Have you been here before?",
  "Is this your first time here?",
  "Do you come here often?",
  "Are you from around here?",
  "What line of work are you in?",
  "What do you do for a living?",
  "How do you know each other?",
  "I couldn't help but notice...",
  "I couldn't help but notice your accent.",
  "I couldn't help but notice you're reading my favourite book.",
  "I couldn't help but notice the sign outside.",
  "I couldn't help but notice you look a bit lost.",
  "I couldn't help but notice we're wearing the same shoes.",
  "I don't think we've met.",
  "Sorry to bother you, but...",
  "Sorry to bother you, but do you know what time it is?",
  "Sorry to bother you, but is this seat taken?",
  "Sorry to bother you, but could you help me with something?",
  "Sorry to bother you, but do you work here?",
  "Sorry to bother you, but is there a chemist nearby?",
  "Mind if I ask you something?",
  "Funny story, actually...",
  "Funny story, actually — I almost didn't come today.",
  "Funny story, actually — I ran into your brother this morning.",
  "Funny story, actually — I locked myself out yesterday.",
  "Funny story, actually — we've been to the same place before.",
  "Funny story, actually — I was just thinking about you.",
  "You'll never guess what happened.",
  "So, get this...",
  "So, get this — she quit her job yesterday.",
  "So, get this — they cancelled the whole event.",
  "So, get this — he showed up three hours late.",
  "So, get this — the price doubled overnight.",
  "So, get this — I bumped into my old teacher at the shop.",
  "Guess what?",
  "You know what's funny?"
];

// Re-engaging and Keeping Conversation Going
const keeping_conversation_phrases = [
  "So anyway, what were you saying?",
  "Sorry, where was I?",
  "Where were we?",
  "What was I saying?",
  "Oh, and another thing...",
  "Oh, and another thing — I forgot to mention the email.",
  "Oh, and another thing — she's bringing her boyfriend.",
  "Oh, and another thing — the deadline changed.",
  "Oh, and another thing — they want us there by nine.",
  "Oh, and another thing — I need your Wi-Fi password.",
  "That's so interesting — how did that happen?",
  "Wait, back up — what do you mean?",
  "Hold on, you skipped the best part!",
  "No, but seriously though...",
  "No, but seriously though, what did he say?",
  "No, but seriously though, are you okay?",
  "No, but seriously though, we need to talk about this.",
  "No, but seriously though, how did you pull that off?",
  "No, but seriously though, that's impressive.",
  "And the best part is...",
  "And the best part is, it was free.",
  "And the best part is, she didn't even notice.",
  "And the best part is, we still made it on time.",
  "And the best part is, he apologised.",
  "And the best part is, I got the job.",
  "You know what the worst part is?",
  "The funny thing is...",
  "The funny thing is, I was just about to say the same thing.",
  "The funny thing is, nobody noticed.",
  "The funny thing is, it actually worked.",
  "The funny thing is, she predicted this would happen.",
  "The funny thing is, I've never even been there.",
  "The weird thing is...",
  "The weird thing is, he didn't seem surprised.",
  "The weird thing is, no one mentioned it.",
  "The weird thing is, it happened twice.",
  "The weird thing is, I had a dream about it.",
  "The weird thing is, she never called back.",
  "The crazy thing is...",
  "The crazy thing is, it all happened in one day.",
  "The crazy thing is, he doesn't even remember.",
  "The crazy thing is, we were standing right there.",
  "The crazy thing is, nobody said anything.",
  "The crazy thing is, it was completely free.",
  "Here's the thing...",
  "Here's the thing — I don't actually disagree with you.",
  "Here's the thing — we don't have enough time.",
  "Here's the thing — nobody asked for this.",
  "Here's the thing — it's not about the money.",
  "Here's the thing — I've already made up my mind."
];

// Casual Greetings and Status
const casual_greetings_status_phrases = [
  "Wassup?",
  "You good?",
  "Wanna grab some food?",
  "You down?",
  "You in?",
  "I'm down",
  "I'm in",
  "Got it?",
  "You serious?",
  "You kidding me?",
  "Yeah, sure",
  "No way!",
  "I have no idea",
  "No clue",
  "Beats me",
  "I'm not sure",
  "Maybe",
  "Probably",
  "I think so",
  "Not really",
  "Sort of",
  "It depends",
  "Absolutely",
  "Exactly",
  "Totally",
  "Definitely",
  "For sure",
  "Got it",
  "I see",
  "Oh, I see",
  "Oh, right",
  "Oh my God",
  "Thank you so much",
  "Thanks a lot",
  "Don't mention it",
  "No problem",
  "No worries",
  "Cool",
  "Awesome",
  "Amazing"
];

// Discourse Markers (Structuring Speech)
const discourse_markers_phrases = [
  "To be honest, I wasn't expecting that.",
  "To be honest, I don't really like it.",
  "To be honest, I'm a bit worried.",
  "To be honest, I have no idea what to do.",
  "To be honest, I'd rather stay home.",
  "The thing is, I can't afford it right now.",
  "The thing is, she never listens.",
  "The thing is, we're running out of time.",
  "The thing is, I already promised someone else.",
  "The thing is, it's more complicated than that.",
  "I think that we should wait.",
  "I think that he's right.",
  "I think that it's too risky.",
  "I think that you're worrying too much.",
  "I think that there's a better way to do this.",
  "I see your point",
  "That's a good point",
  "I know what you mean",
  "That makes sense",
  "I'd say it's worth a try.",
  "I'd say we need more information.",
  "I'd say about two hours.",
  "I'd say she's probably stuck in traffic.",
  "I'd say that's the best option.",
  "Well, I'm not sure about that.",
  "Well, that's interesting.",
  "Well, let me think.",
  "Well, what do you want to do?",
  "Well, it could be worse.",
  "Actually, I changed my mind.",
  "Actually, I was just about to leave.",
  "Actually, that's not quite right.",
  "Actually, I prefer the other one.",
  "Actually, now that you mention it, I agree.",
  "Basically, we ran out of time.",
  "Basically, it's not worth it.",
  "Basically, he just quit.",
  "Basically, it's the same thing.",
  "Basically, we need to start over.",
  "It's just frustrating, you know?",
  "I'm really tired, you know?",
  "Things have been tough, you know?",
  "I don't want to bother anyone, you know?",
  "It's hard to explain, you know?",
  "Anyway, I should get going.",
  "Anyway, that's not important right now.",
  "Anyway, how have you been?",
  "Anyway, let's move on.",
  "Anyway, the point is we need to decide.",
  "That reminds me, I need to call her.",
  "That reminds me, did you send that email?",
  "That reminds me of a funny story.",
  "That reminds me, we have a meeting at 3.",
  "That reminds me, I forgot to buy milk.",
  "Long story short, we got lost.",
  "Long story short, it didn't work out.",
  "Long story short, I quit.",
  "Long story short, everything's fine now.",
  "Long story short, he apologized and we moved on.",
  "Bottom line is, we can't afford it.",
  "Bottom line is, you need to decide.",
  "Bottom line is, it's your choice.",
  "Bottom line is, we're running out of options.",
  "Bottom line is, something has to change.",
  "At the end of the day, it's your decision.",
  "At the end of the day, we all want the same thing.",
  "At the end of the day, what matters is that you tried.",
  "At the end of the day, family comes first.",
  "At the end of the day, you have to do what's right for you.",
  "Between you and me, I don't think he's ready.",
  "Between you and me, I'm thinking of quitting.",
  "Between you and me, she's not very good at her job.",
  "Between you and me, I'm a bit worried.",
  "Between you and me, I think they're making a mistake."
];

// Social Maintenance
const social_maintenance_phrases = [
  "How's work going?",
  "I'm swamped with work",
  "I'll be right back",
  "I'll keep you posted",
  "What's new?",
  "Long time no see",
  "Nice to meet you",
  "Make yourself at home",
  "Don't be a stranger",
  "We should catch up",
  "How've you been?",
  "What have you been up to?",
  "Keeping busy?",
  "Same old, same old",
  "Can't complain",
  "Not much"
];

// Problems and Apologies
const problems_apologies_phrases = [
  "There's a problem",
  "Something came up",
  "I made a mistake",
  "That was my fault",
  "I completely forgot",
  "It slipped my mind",
  "Don't worry about it",
  "We're good now",
  "My bad",
  "Sorry about that",
  "I apologize",
  "I didn't mean to offend you.",
  "I didn't mean to interrupt.",
  "I didn't mean to break it.",
  "I didn't mean to forget.",
  "I didn't mean to make you uncomfortable.",
  "Excuse me"
];

// Wishes and Preferences
const wishes_preferences_phrases = [
  "I wish I could help.",
  "I wish I'd known earlier.",
  "I wish things were different.",
  "I wish I had more time.",
  "I wish you were here.",
  "I hope so",
  "Fingers crossed",
  "You've got this",
  "I have a good feeling about this",
  "I prefer tea over coffee.",
  "I prefer working alone.",
  "I prefer to wait until tomorrow.",
  "I prefer the blue one.",
  "I prefer staying in on weekends.",
  "I'd rather stay in tonight.",
  "I'd rather not talk about it.",
  "I'd rather walk than take the bus.",
  "I'd rather you didn't.",
  "I'd rather wait and see.",
  "It's not really my thing",
  "It's not my cup of tea",
  "Either is fine with me",
  "I'm easy",
  "It's up to you"
];

// Assumptions and Probability
const assumptions_probability_phrases = [
  "I assume that you've already heard.",
  "I assume that she's coming too.",
  "I assume that we're meeting at 5.",
  "I assume that everything's okay.",
  "I assume that you know what you're doing.",
  "I bet that he forgot.",
  "I bet that she's running late.",
  "I bet that it's expensive.",
  "I bet that you're tired.",
  "I bet that they already left.",
  "Chances are that it'll rain.",
  "Chances are that he won't come.",
  "Chances are that she already knows.",
  "Chances are that we'll be late.",
  "Chances are that it's already sold out.",
  "Most likely, they're stuck in traffic.",
  "Most likely, he's still asleep.",
  "Most likely, it's sold out.",
  "Most likely, she'll say yes.",
  "Most likely, we won't hear back until Monday.",
  "Generally speaking, people prefer morning meetings.",
  "Generally speaking, it takes about an hour.",
  "Generally speaking, I avoid fast food.",
  "Generally speaking, the weather's nice here.",
  "Generally speaking, things tend to work out.",
  "Usually, I take the bus.",
  "Usually, she's on time.",
  "Usually, it's not this crowded.",
  "Usually, they close at 6.",
  "Usually, he calls before coming over.",
  "I'm not entirely sure",
  "Your guess is as good as mine",
  "It's hard to say",
  "It's up in the air",
  "Only time will tell",
  "We'll have to wait and see"
];

// Future Intentions
const future_intentions_phrases = [
  "I'm planning to visit my parents next month.",
  "I'm planning to start a new project.",
  "I'm planning to learn Spanish.",
  "I'm planning to move to a bigger apartment.",
  "I'm planning to take some time off in July.",
  "My goal is to finish by Friday.",
  "My goal is to save more money this year.",
  "My goal is to get promoted.",
  "My goal is to run a marathon.",
  "My goal is to read one book a month.",
  "I'm looking forward to the weekend.",
  "I'm looking forward to seeing you.",
  "I'm looking forward to trying that restaurant.",
  "I'm looking forward to the holidays.",
  "I'm looking forward to starting the new job.",
  "I can't wait to see the results.",
  "I can't wait to tell you what happened.",
  "I can't wait to go on vacation.",
  "I can't wait to meet him.",
  "I can't wait to try the new place."
];

// Comparison and Contrast
const comparison_contrast_phrases = [
  "It's not as easy as it looks.",
  "It's not as bad as you think.",
  "It's not as expensive as I thought.",
  "It's not as cold as yesterday.",
  "It's not as far as I expected.",
  "It's much better than the old version.",
  "It's much better than I expected.",
  "It's much better than last time.",
  "It's much better than nothing.",
  "It's much better than what we had before.",
  "There's no comparison"
];

// Advice and Suggestions
const advice_suggestions_phrases = [
  "You should see a doctor.",
  "You should try this.",
  "You should tell her the truth.",
  "You should be more careful.",
  "You should go for it.",
  "If I were you, I'd apologize.",
  "If I were you, I'd take the job.",
  "If I were you, I wouldn't worry about it.",
  "If I were you, I'd leave now.",
  "If I were you, I'd talk to her about it.",
  "Have you considered looking for a new job?",
  "Have you considered moving closer?",
  "Have you considered talking to a professional?",
  "Have you considered other options?",
  "Have you considered taking a break first?",
  "Have you tried turning it off and on again?",
  "Have you tried calling customer service?",
  "Have you tried asking for help?",
  "Have you tried the new restaurant downtown?",
  "Have you tried doing it the other way?",
  "It might be worth checking again.",
  "It might be worth asking.",
  "It might be worth waiting a bit longer.",
  "It might be worth investing in.",
  "It might be worth giving it another shot.",
  "You should give it a try",
  "What have you got to lose?",
  "Do yourself a favour",
  "Be careful",
  "Watch out"
];

// Compliments and Encouragement
const compliments_encouragement_phrases = [
  "You look great",
  "I love your shoes!",
  "I love your sense of humour.",
  "I love your new haircut.",
  "I love your cooking.",
  "I love your attitude.",
  "Well done",
  "You should be proud",
  "I'm so proud of you",
  "You're awesome",
  "You can do it",
  "Keep it up",
  "Don't give up",
  "Hang in there",
  "You're doing great"
];

// Past Reflection
const past_reflection_phrases = [
  "I used to live in London.",
  "I used to play tennis.",
  "I used to work there.",
  "I used to think the same thing.",
  "I used to hate vegetables.",
  "I remember when we first met.",
  "I remember you telling me that.",
  "I remember the day clearly.",
  "I remember how nervous I was.",
  "I remember thinking it was a bad idea.",
  "Looking back, I should have been more patient.",
  "Looking back, it was the right decision.",
  "Looking back, those were good times.",
  "Looking back, I learned a lot.",
  "Looking back, I wouldn't change a thing.",
  "Those were the days",
  "Back in the day, things were different.",
  "Back in the day, we used to walk everywhere.",
  "Back in the day, I was much fitter.",
  "Back in the day, nobody had smartphones.",
  "Back in the day, we'd hang out at the park every weekend.",
  "If only I had known earlier!",
  "If only I had known you were coming.",
  "If only I had known it would be this hard.",
  "If only I had known the truth.",
  "If only I had known what was going to happen."
];

// Arrangements and Scheduling
const arrangements_scheduling_phrases = [
  "What are you doing later?",
  "Got any plans?",
  "That sounds good",
  "Sounds like a plan",
  "I'm game",
  "Count me in",
  "I'd love to",
  "I wish I could",
  "I can't make it",
  "Something came up",
  "Let's make plans",
  "Does that work for you?",
  "We need to reschedule",
  "Let's do it",
  "I'm going for it",
  "I've made up my mind",
  "I need to think about it",
  "I'll get back to you on that",
  "What time suits you?",
  "When works for you?",
  "I'm free on Tuesday afternoon.",
  "I'm free on weekends.",
  "I'm free on the 15th.",
  "I'm free on Thursday after 3.",
  "I'm free on Monday morning.",
  "How does 3 p.m. sound?",
  "How does Italian food sound?",
  "How does next Friday sound?",
  "How does this plan sound to you?",
  "How does meeting at the café sound?",
  "Let me check my schedule",
  "I'm afraid I can't",
  "I'd rather not",
  "Maybe another time",
  "Not this time",
  "I'll pass"
];

// Farewells
const farewells_phrases = [
  "See you later",
  "Catch you later",
  "Talk to you later",
  "Have a good one",
  "Take care",
  "Take it easy",
  "All the best",
  "I should get going",
  "I need to run",
  "It was great seeing you",
  "Nice talking to you"
];

// Pause and Fillers
const pause_fillers_phrases = [
  "Um... I'm not sure about that.",
  "Um... can I get back to you on that?",
  "Um... I think it was last Tuesday.",
  "Um... what was the question again?",
  "Um... let me check.",
  "Uh... I don't think so.",
  "Uh... that doesn't sound right.",
  "Uh... give me a moment.",
  "Uh... I forgot what I was going to say.",
  "Uh... where were we?",
  "Let me think... maybe we could try next week?",
  "Let me think... I believe it was on Tuesday.",
  "Let me think... what was I going to say?",
  "Let me think... yeah, I think that could work.",
  "Let me think... no, that's not right either.",
  "Give me a second",
  "Hang on",
  "Hold on a sec"
];

// Continuation Prompts
const continuation_prompts_phrases = [
  "Go on",
  "Keep going",
  "I'm listening"
];

// Acknowledgment and Understanding
const acknowledgment_understanding_phrases = [
  "That's interesting",
  "No kidding",
  "So you're saying it's too late?",
  "So you're saying you don't want to go?",
  "So you're saying we should wait?",
  "So you're saying there's still a chance?",
  "So you're saying it's not going to work?",
  "You mean like a restaurant?",
  "You mean she already knows?",
  "You mean it's free?",
  "You mean we have to start over?",
  "You mean right now?",
  "In other words, we failed.",
  "In other words, you're not interested.",
  "In other words, it's impossible.",
  "In other words, we need more money.",
  "In other words, we're back to square one.",
  "Just to clarify, you're saying no?",
  "Just to clarify, are we meeting at 6 or 7?",
  "Just to clarify, is this included in the price?",
  "Just to clarify, who's responsible for this?",
  "Just to clarify, when's the actual deadline?",
  "Let me get this straight",
  "Does that make sense?",
  "Do you follow?",
  "Are you with me?",
  "You get what I mean?",
  "Know what I'm saying?"
];

// Agreement and Disagreement
const agreement_disagreement_phrases = [
  "I couldn't agree more",
  "That's not quite right",
  "I'm not so sure about that",
  "I see it differently",
  "You've got a point there",
  "With all due respect, I disagree.",
  "With all due respect, that's not how it works.",
  "With all due respect, you weren't there.",
  "With all due respect, I think there's a better way.",
  "With all due respect, I don't think that's fair.",
  "No offense, but that idea won't work.",
  "No offense, but you're being a bit harsh.",
  "No offense, but I think you're wrong.",
  "No offense, but this looks terrible.",
  "No offense, but maybe you should get a second opinion.",
  "Let's agree to disagree",
  "I totally agree",
  "I'm with you on that",
  "Fair enough",
  "That's true",
  "I hear you",
  "I see what you're saying"
];

// Topic Shift
const topic_shift_phrases = [
  "By the way, did you see the email I sent?",
  "By the way, how's your sister doing?",
  "By the way, are you free on Friday?",
  "By the way, have you eaten yet?",
  "By the way, I forgot to mention something.",
  "Speaking of which, have you talked to John?",
  "Speaking of which, I need to buy groceries.",
  "Speaking of which, how did the interview go?",
  "Speaking of which, did you ever hear back from them?",
  "Speaking of which, I ran into your neighbor yesterday.",
  "On a different note",
  "Before I forget, here's your book back.",
  "Before I forget, we need to pay the bills.",
  "Before I forget, Sarah called you earlier.",
  "Before I forget, the meeting's been rescheduled.",
  "Before I forget, happy birthday tomorrow!"
];

// Proposals and Plans (How about - Let's - Why don't we - Shall we - We could)
const proposals_plans_phrases = [
  "How about we meet at 6?",
  "How about trying the other one?",
  "How about this: I'll call you tomorrow?",
  "How about pizza for dinner?",
  "How about we take a different route?",
  "What about John? Is he coming?",
  "What about trying a different approach?",
  "What about next Tuesday instead?",
  "What about your family? What do they think?",
  "What about splitting the bill?",
  "Why don't we take a break?",
  "Why don't we ask for directions?",
  "Why don't we split the cost?",
  "Why don't we just forget about it?",
  "Why don't we sleep on it and decide tomorrow?",
  "Let's go!",
  "Let's try again.",
  "Let's see what happens.",
  "Let's not argue about this.",
  "Let's grab lunch together.",
  "Shall we go?",
  "Shall we start?",
  "Shall we order now?",
  "Shall we take a taxi?",
  "Shall we call it a day?",
  "We could always come back later.",
  "We could try calling again.",
  "We could ask someone for help.",
  "We could just reschedule.",
  "We could meet halfway."
];

// Offering Help
const offering_help_phrases = [
  "Need a hand?",
  "Let me help you with that",
  "I can do that for you",
  "Allow me"
];

// Difficulty and Problems
const difficulty_problems_phrases = [
  "I'm having trouble with my computer.",
  "I'm having trouble with this assignment.",
  "I'm having trouble understanding this.",
  "I'm having trouble sleeping lately.",
  "I'm having trouble making up my mind.",
  "This is tricky",
  "I can't seem to find my keys.",
  "I can't seem to make it work.",
  "I can't seem to remember his name.",
  "I can't seem to concentrate today.",
  "I can't seem to get this right.",
  "I'm stuck",
  "I don't get it",
  "Let me see if I got this",
  "That explains it",
  "Now I get it",
  "I'm struggling with this concept.",
  "I'm struggling with the workload.",
  "I'm struggling with my confidence.",
  "I'm struggling with this decision.",
  "I'm struggling with time management."
];

// Time References
const time_references_phrases = [
  "In a bit",
  "In a minute",
  "Right now",
  "Just now",
  "A while ago",
  "The other day",
  "Not long ago"
];

// Emotional Reactions
const emotional_reactions_phrases = [
  "Oh no!",
  "That's great!",
  "Good for you!",
  "I'm sorry to hear that",
  "Congrats!",
  "That's too bad",
  "Bummer"
];

// Tentative and Uncertain
const tentative_uncertain_phrases = [
  "I might be a bit late.",
  "I might need your help.",
  "I might change my mind.",
  "I might stay home instead.",
  "I might take the day off.",
  "I'll try to make it.",
  "I'll try to finish it tonight.",
  "I'll try to call you back.",
  "I'll try to be there on time.",
  "I'll try to figure it out.",
  "Hopefully, it won't rain.",
  "Hopefully, she'll understand.",
  "Hopefully, everything works out.",
  "Hopefully, we can meet soon.",
  "Hopefully, the package arrives today.",
  "We'll see",
  "I'm not sure yet",
  "It's tentative"
];

// Polite Interruptions and Transitions
const polite_interruptions_transitions_phrases = [
  "Sorry to interrupt",
  "Can I just say something quickly?",
  "Can I just say, you did a great job!",
  "Can I just say, I think that's unfair.",
  "Can I just say, I really appreciate your help.",
  "Can I just say, this has been amazing.",
  "Quick question",
  "Before you continue, can I clarify something?",
  "Before you continue, I have a question.",
  "Before you continue, did you check with John?",
  "Before you continue, I think I missed something.",
  "Before you continue, can we go back to the last point?"
];

// Exit Strategies
const exit_strategies_phrases = [
  "Anyway, I should go",
  "I won't keep you",
  "I'll let you go"
];

// Empathy and Understanding
const empathy_understanding_phrases = [
  "I understand",
  "I get it",
  "That must be hard",
  "I feel you",
  "I can imagine"
];

// Indirect Requests (Wondering - Chance - Think you could)
const indirect_requests_phrases = [
  "I was wondering if you could help me.",
  "I was wondering if you're free tonight.",
  "I was wondering if I could borrow your car.",
  "I was wondering if you've heard from Sarah.",
  "I was wondering if you'd be interested in joining us.",
  "Is there any chance you could stay late?",
  "Is there any chance we could reschedule?",
  "Is there any chance this is a mistake?",
  "Is there any chance you're free tomorrow?",
  "Is there any chance you could lend me a hand?",
  "Do you think you could give me a hand?",
  "Do you think you could speak quieter?",
  "Do you think you could email that to me?",
  "Do you think you could explain it again?",
  "Do you think you could drop me off on the way?"
];

// Hedging (Softening statements)
const hedging_phrases = [
  "I hate to say it, but...",
  "I hate to say it, but this might not work.",
  "I hate to say it, but you're probably right.",
  "I hate to say it, but we're out of time.",
  "I hate to say it, but that's not realistic.",
  "I hate to say it, but I don't agree.",
  "Correct me if I'm wrong, but...",
  "Correct me if I'm wrong, but this was already decided.",
  "Correct me if I'm wrong, but we tried that before.",
  "Correct me if I'm wrong, but that's not what you said.",
  "Correct me if I'm wrong, but the deadline is tomorrow.",
  "Correct me if I'm wrong, but this seems rushed.",
  "To be perfectly honest with you...",
  "To be perfectly honest with you, I'm not convinced.",
  "To be perfectly honest with you, I don't like the idea.",
  "To be perfectly honest with you, I expected more.",
  "To be perfectly honest with you, I'm exhausted.",
  "To be perfectly honest with you, I disagree.",
  "As far as I know...",
  "As far as I know, the meeting is still on.",
  "As far as I know, she hasn't replied.",
  "As far as I know, that's the final version.",
  "As far as I know, he's out of town.",
  "As far as I know, everything is ready.",
  "Don't quote me on this, but...",
  "Don't quote me on this, but I think it's delayed.",
  "Don't quote me on this, but she might quit.",
  "Don't quote me on this, but that deal fell through.",
  "Don't quote me on this, but he got promoted.",
  "Don't quote me on this, but the price went up.",
  "If I recall correctly...",
  "If I recall correctly, we met last year.",
  "If I recall correctly, she handled that project.",
  "If I recall correctly, that's not allowed.",
  "If I recall correctly, the deadline was Friday.",
  "If I recall correctly, he approved it.",
  "It's my understanding that...",
  "It's my understanding that this is confidential.",
  "It's my understanding that she's in charge.",
  "It's my understanding that we're waiting on approval.",
  "It's my understanding that the budget was cut.",
  "It's my understanding that this is optional.",
  "I was under the impression that...",
  "I was under the impression that you were coming.",
  "I was under the impression that it was canceled.",
  "I was under the impression that she handled this.",
  "I was under the impression that we agreed.",
  "I was under the impression that today was the deadline."
];

// Vague Language
const vague_language_phrases = [
  "...and that kind of thing.",
  "We talked about work, deadlines, and that kind of thing.",
  "She likes art, music, and that kind of thing.",
  "They sell snacks, drinks, and that kind of thing.",
  "We need pens, paper, and that kind of thing.",
  "He mentioned taxes, bills, and that kind of thing.",
  "...or something like that.",
  "It costs fifty bucks or something like that.",
  "We'll meet at six or something like that.",
  "He said Tuesday or something like that.",
  "It'll take an hour or something like that.",
  "She's twenty-five or something like that.",
  "...give or take.",
  "It's ten minutes, give or take.",
  "About fifty people, give or take.",
  "A hundred dollars, give or take.",
  "Two weeks, give or take.",
  "Three years, give or take.",
  "...stuff like that.",
  "We talked about relationships, stuff like that.",
  "She buys books, journals, stuff like that.",
  "They sell clothes, accessories, stuff like that.",
  "He likes sports, fitness, stuff like that.",
  "We need tools, supplies, stuff like that.",
  "Roughly speaking...",
  "Roughly speaking, it'll take two hours.",
  "Roughly speaking, we need about ten people.",
  "Roughly speaking, the cost is a thousand.",
  "Roughly speaking, it's almost done.",
  "Roughly speaking, it's a good plan."
];

// Transition Phrases
const transition_phrases = [
  "Having said that...",
  "Having said that, I still agree with you.",
  "Having said that, there are risks.",
  "Having said that, we should try.",
  "Having said that, I'm not fully convinced.",
  "Having said that, let's move on.",
  "On the flip side...",
  "On the flip side, it could save time.",
  "On the flip side, it's more expensive.",
  "On the flip side, it's safer.",
  "On the flip side, it's less flexible.",
  "On the flip side, it might work better.",
  "That being said...",
  "That being said, I understand your point.",
  "That being said, we should be careful.",
  "That being said, I'm open to it.",
  "That being said, it's not ideal.",
  "That being said, let's try it.",
  "To make a long story short...",
  "To make a long story short, we missed the deadline.",
  "To make a long story short, it didn't work.",
  "To make a long story short, she said no.",
  "To make a long story short, we agreed.",
  "To make a long story short, it was canceled.",
  "In the grand scheme of things...",
  "In the grand scheme of things, it doesn't matter.",
  "In the grand scheme of things, it's a small issue.",
  "In the grand scheme of things, we'll be fine.",
  "In the grand scheme of things, it's minor.",
  "In the grand scheme of things, it won't change much.",
  "In the meantime...",
  "In the meantime, let's start without them.",
  "In the meantime, I'll send an email.",
  "In the meantime, we can prepare.",
  "In the meantime, just wait.",
  "In the meantime, I'll follow up."
];

// Sentence Frames
const sentence_frame_phrases = [
  "I was just about to...",
  "I was just about to call you.",
  "I was just about to leave.",
  "I was just about to send that.",
  "I was just about to ask you.",
  "I was just about to start.",
  "It's only a matter of time before...",
  "It's only a matter of time before they notice.",
  "It's only a matter of time before it breaks.",
  "It's only a matter of time before she calls.",
  "It's only a matter of time before we win.",
  "It's only a matter of time before they change it.",
  "I can't help but think that...",
  "I can't help but think that this is wrong.",
  "I can't help but think that we missed something.",
  "I can't help but think that she's right.",
  "I can't help but think that it's risky.",
  "I can't help but think that it's too late.",
  "There's no point in...",
  "There's no point in arguing.",
  "There's no point in waiting.",
  "There's no point in stressing.",
  "There's no point in going back.",
  "There's no point in guessing.",
  "It's not that I don't like it, it's just...",
  "It's not that I don't like it, it's just too expensive.",
  "It's not that I don't like it, it's just impractical.",
  "It's not that I don't like it, it's just risky.",
  "It's not that I don't like it, it's just unnecessary.",
  "It's not that I don't like it, it's just bad timing.",
  "I hate to be the one to tell you, but...",
  "I hate to be the one to tell you, but it's canceled.",
  "I hate to be the one to tell you, but we're late.",
  "I hate to be the one to tell you, but it failed.",
  "I hate to be the one to tell you, but she said no.",
  "I hate to be the one to tell you, but it's over."
];

// Hypotheticals (Extended frames)
const hypotheticals_extended_phrases = [
  "If I could go back in time, I'd...",
  "If I could go back in time, I'd change that decision.",
  "If I could go back in time, I'd try harder.",
  "If I could go back in time, I'd say no.",
  "If I could go back in time, I'd invest earlier.",
  "If I could go back in time, I'd listen more.",
  "Had I known, I would have...",
  "Had I known, I would have said something.",
  "Had I known, I would have prepared.",
  "Had I known, I would have stayed.",
  "Had I known, I would have warned you.",
  "Had I known, I would have done it differently."
];

// Past Participle - Describing States and Results
const past_participle_states_phrases = [
  "It's broken.",
  "It's done.",
  "It's gone.",
  "It's been cancelled.",
  "It's already been decided.",
  "It's been taken care of.",
  "I'm done.",
  "I'm exhausted.",
  "I'm confused.",
  "I'm lost.",
  "I'm stuck.",
  "I'm impressed.",
  "I'm convinced.",
  "I'm disappointed.",
  "I'm overwhelmed.",
  "I'm surprised.",
  "I'm concerned.",
  "I'm involved in the project.",
  "I'm committed to this.",
  "I'm used to it.",
  "I'm not used to...",
  "I'm not used to waking up this early.",
  "I'm not used to working weekends.",
  "I'm not used to the cold weather.",
  "I'm not used to driving on the left.",
  "I'm not used to being the new person."
];

// Get + Past Participle
const get_past_participle_phrases = [
  "I got stuck in traffic.",
  "I got confused.",
  "I got fired.",
  "I got promoted.",
  "I got lost.",
  "I got invited to the party.",
  "We got delayed.",
  "She got rejected.",
  "He got arrested.",
  "They got divorced.",
  "It got cancelled.",
  "I almost got hit by a car.",
  "We got ripped off.",
  "He got transferred to another office.",
  "She got accepted into the programme."
];

// Present Perfect Statements (Have - Has + past participle)
const present_perfect_statements_phrases = [
  "I've never seen anything like it.",
  "I've been there before.",
  "I've already done it.",
  "I've heard that before.",
  "I've known him for years.",
  "I've thought about it.",
  "I've made up my mind.",
  "I've had enough.",
  "I've changed my mind.",
  "I've been meaning to...",
  "I've been meaning to tell you.",
  "I've been meaning to call her.",
  "I've been meaning to fix that.",
  "I've been meaning to ask you something.",
  "I've been meaning to bring this up.",
  "I've been thinking about what you said.",
  "I've been working on it.",
  "I've been looking everywhere for you.",
  "I've been told that...",
  "I've been told that the office is moving.",
  "I've been told that she's leaving.",
  "I've been told that the budget was cut.",
  "I've been told that we need to reapply.",
  "I've been told that it's not possible.",
  "She's gone home already.",
  "He's left the building.",
  "They've already started.",
  "We've run out of time.",
  "It's been ages since we last spoke.",
  "It's been a long day.",
  "It's been a while.",
  "It's been great working with you."
];

// Passive Voice Chunks
const passive_voice_phrases = [
  "I was told that...",
  "I was told that the meeting was cancelled.",
  "I was told that she'd be here by now.",
  "I was told that it was free.",
  "I was told that we had to wait.",
  "I was told that there was a problem.",
  "I wasn't informed.",
  "I was given the wrong information.",
  "I was asked to...",
  "I was asked to lead the project.",
  "I was asked to stay late.",
  "I was asked to give a presentation.",
  "I was asked to fill in for her.",
  "I was asked to keep it confidential.",
  "It was supposed to be ready by now.",
  "The meeting was moved to Friday.",
  "The flight was delayed.",
  "The order was cancelled.",
  "It's been rescheduled.",
  "We were warned about this.",
  "You're not allowed to do that.",
  "It's not allowed.",
  "It's considered rude.",
  "It's expected to rain.",
  "It's been approved.",
  "It's been confirmed."
];

// Obligation and Necessity (Have to - Need to - Should - Supposed to)
const obligation_necessity_phrases = [
  "I have to go.",
  "I've got to run.",
  "I need to get this done.",
  "You have to try this.",
  "We need to talk.",
  "I really should get going.",
  "You're supposed to be there by 9.",
  "We're meant to finish by Friday.",
  "I was supposed to...",
  "I was supposed to call her.",
  "I was supposed to be there an hour ago.",
  "I was supposed to finish this yesterday.",
  "I was supposed to meet him for lunch.",
  "I was supposed to hear back by now.",
  "You shouldn't have to deal with that.",
  "You don't have to do that.",
  "You didn't have to do that.",
  "I had to cancel.",
  "I had no choice.",
  "I'm meant to...",
  "I'm meant to be working right now.",
  "I'm meant to pick her up at five.",
  "I'm meant to hand this in tomorrow.",
  "I'm meant to be on a diet.",
  "I'm meant to call them back today."
];

// Reported Speech (Telling What Someone Said)
const reported_speech_phrases = [
  "She said she'd be here by now.",
  "He told me not to worry.",
  "They said it was fine.",
  "She mentioned that she was leaving.",
  "He asked me if I was coming.",
  "She said she'd think about it.",
  "Apparently...",
  "Apparently, he's not coming.",
  "Apparently, they've already decided.",
  "Apparently, it's been postponed.",
  "Apparently, she didn't get the message.",
  "Apparently, we're not invited.",
  "I heard he got a new job.",
  "Rumour has it...",
  "Rumour has it they're getting married.",
  "Rumour has it the company's being sold.",
  "Rumour has it she's been offered the position.",
  "Rumour has it he's thinking of retiring.",
  "Rumour has it the office is relocating.",
  "Word is that...",
  "Word is that they're shutting down.",
  "Word is that she got the promotion.",
  "Word is that there are layoffs coming.",
  "Word is that the deal fell through.",
  "Word is that he's moving abroad.",
  "Someone told me that...",
  "Someone told me that the restaurant closed.",
  "Someone told me that you were looking for me.",
  "Someone told me that the deadline changed.",
  "Someone told me that she's not coming.",
  "Someone told me that we have to resubmit."
];

// Cause and Effect (Explaining Why)
const cause_effect_phrases = [
  "That's why I called.",
  "That's why I'm asking.",
  "That's the reason I left.",
  "It's because of the traffic.",
  "I ended up...",
  "I ended up staying home.",
  "I ended up taking a taxi.",
  "I ended up changing my mind.",
  "I ended up apologising.",
  "I ended up working late.",
  "It turns out...",
  "It turns out he was right.",
  "It turns out she already knew.",
  "It turns out we didn't need it.",
  "It turns out the whole thing was a mistake.",
  "It turns out they were lying.",
  "It turned out to be a mistake.",
  "It turned out better than expected.",
  "It led to a lot of problems.",
  "That's how it happened.",
  "So that's what happened.",
  "No wonder...",
  "No wonder he's upset.",
  "No wonder it didn't work.",
  "No wonder she left early.",
  "No wonder they're behind schedule.",
  "No wonder you're tired."
];

// Expressing Surprise and Disbelief
const surprise_disbelief_phrases = [
  "You're kidding!",
  "Get out of here!",
  "Shut up!",
  "I had no idea.",
  "I didn't see that coming.",
  "That came out of nowhere.",
  "Who would've thought?",
  "I never would've guessed.",
  "Would you believe it?",
  "Can you imagine?",
  "That's unbelievable.",
  "That blows my mind.",
  "That's insane.",
  "I'm speechless.",
  "You've got to be kidding me.",
  "I can't believe you just said that.",
  "Wait, what?",
  "Hang on, are you serious?",
  "That's the last thing I expected."
];

// Complaining and Expressing Frustration
const complaining_frustration_phrases = [
  "I'm sick and tired of this.",
  "I'm fed up with it.",
  "I've had it.",
  "This is ridiculous.",
  "This is getting out of hand.",
  "This is a nightmare.",
  "I can't take it anymore.",
  "It drives me crazy.",
  "It gets on my nerves.",
  "It's doing my head in.",
  "What a pain.",
  "What a waste of time.",
  "Give me a break.",
  "For goodness' sake.",
  "I'm so done with this.",
  "I can't be bothered.",
  "It's not worth the hassle.",
  "This is beyond a joke.",
  "I'm at my wit's end."
];

// Reassuring and Calming
const reassuring_calming_phrases = [
  "Don't worry about it.",
  "It'll be fine.",
  "It's no big deal.",
  "It's not the end of the world.",
  "These things happen.",
  "Don't beat yourself up about it.",
  "It could be worse.",
  "There's nothing to worry about.",
  "It'll sort itself out.",
  "Everything happens for a reason.",
  "Take it one step at a time.",
  "One thing at a time.",
  "We'll figure it out.",
  "We'll cross that bridge when we come to it.",
  "Let's not get ahead of ourselves."
];

// Expressing Relief
const expressing_relief_phrases = [
  "Thank goodness!",
  "That's a relief.",
  "I'm so relieved.",
  "I'm glad that's over.",
  "That was a close call.",
  "What a relief!",
  "I was worried for a moment.",
  "I can finally relax.",
  "That's a weight off my shoulders.",
  "I was starting to panic."
];

// Expressing Regret
const expressing_regret_phrases = [
  "I should've known better.",
  "I shouldn't have said that.",
  "I wish I hadn't...",
  "I wish I hadn't said anything.",
  "I wish I hadn't left so early.",
  "I wish I hadn't been so stubborn.",
  "I wish I hadn't ignored the warning.",
  "I wish I hadn't waited so long.",
  "I regret not...",
  "I regret not saying goodbye.",
  "I regret not taking the opportunity.",
  "I regret not being more honest.",
  "I regret not asking for help sooner.",
  "I regret not spending more time with her.",
  "If only I hadn't...",
  "If only I hadn't lost my temper.",
  "If only I hadn't sent that message.",
  "If only I hadn't been late.",
  "If only I hadn't trusted him.",
  "If only I hadn't given up so easily.",
  "I could kick myself.",
  "What was I thinking?",
  "I'll never make that mistake again."
];

// Expressing Gratitude
const expressing_gratitude_phrases = [
  "I really appreciate it.",
  "I can't thank you enough.",
  "That means a lot to me.",
  "I owe you one.",
  "I'm grateful for your help.",
  "You've been so helpful.",
  "You didn't have to do that.",
  "That was really kind of you.",
  "I don't know what I'd do without you.",
  "You're a lifesaver."
];

// Expressing Annoyance (Mild)
const expressing_annoyance_phrases = [
  "That's annoying.",
  "How annoying.",
  "That's a bit much.",
  "That's a bit of a pain.",
  "Oh, come on.",
  "Are you having a laugh?",
  "You can't be serious.",
  "That's not on.",
  "That's the last thing I need.",
  "I could've done without that.",
  "Great, just what I needed.",
  "Typical.",
  "Figures.",
  "Of course it had to happen today.",
  "Just my luck."
];

// Expressing Hope
const expressing_hope_phrases = [
  "Fingers crossed.",
  "Let's hope for the best.",
  "Here's hoping.",
  "With any luck...",
  "With any luck, we'll be done by Friday.",
  "With any luck, she'll say yes.",
  "With any luck, the weather will hold up.",
  "With any luck, they won't notice.",
  "With any luck, we'll get there on time.",
  "I'm keeping my fingers crossed.",
  "I'm hoping for the best.",
  "I'm cautiously optimistic.",
  "I really hope it works out.",
  "There's still hope.",
  "Don't lose hope."
];

// Making Promises and Commitments
const promises_commitments_phrases = [
  "I promise I'll be there.",
  "I give you my word.",
  "I won't let you down.",
  "You can count on me.",
  "I'll make it up to you.",
  "I'll take care of it.",
  "Leave it to me.",
  "Consider it done.",
  "You have my word.",
  "I'll make sure it gets done."
];

// Expressing Certainty and Uncertainty
const certainty_uncertainty_phrases = [
  "I'm positive.",
  "I'm a hundred percent sure.",
  "There's no doubt about it.",
  "Without a doubt.",
  "I couldn't be more certain.",
  "I have no doubt.",
  "I'm fairly certain.",
  "I'm pretty sure.",
  "If I'm not mistaken...",
  "If I'm not mistaken, he's the one who started it.",
  "If I'm not mistaken, the meeting is at two.",
  "If I'm not mistaken, she used to work here.",
  "If I'm not mistaken, that's his brother.",
  "If I'm not mistaken, we've been here before.",
  "Unless I'm wrong...",
  "Unless I'm wrong, the deadline is Friday.",
  "Unless I'm wrong, she already submitted it.",
  "Unless I'm wrong, he's not coming.",
  "Unless I'm wrong, this was approved last week.",
  "Unless I'm wrong, we don't need a reservation.",
  "As far as I can tell...",
  "As far as I can tell, everything's fine.",
  "As far as I can tell, nobody noticed.",
  "As far as I can tell, it's working.",
  "As far as I can tell, she's not interested.",
  "As far as I can tell, we're on track."
];

// Warning and Cautioning
const warning_cautioning_phrases = [
  "I wouldn't do that if I were you.",
  "Be careful what you wish for.",
  "Don't push your luck.",
  "You're playing with fire.",
  "Don't say I didn't warn you.",
  "Mark my words.",
  "Just a heads up...",
  "Just a heads up, she's in a bad mood.",
  "Just a heads up, the boss is coming.",
  "Just a heads up, the deadline's been moved.",
  "Just a heads up, they changed the rules.",
  "Just a heads up, the road's closed.",
  "Fair warning...",
  "Fair warning, it's going to be cold.",
  "Fair warning, it takes ages.",
  "Fair warning, she's quite direct.",
  "Fair warning, the food is really spicy.",
  "Fair warning, it's a long drive.",
  "I'm just saying...",
  "I'm just saying, it might not be the best idea.",
  "I'm just saying, you should think about it.",
  "I'm just saying, there's still time to change your mind.",
  "I'm just saying, don't rush into it.",
  "I'm just saying, it wouldn't hurt to ask.",
  "Just so you know...",
  "Just so you know, I'm leaving early today.",
  "Just so you know, the rules have changed.",
  "Just so you know, I've already spoken to him.",
  "Just so you know, she's not happy about it.",
  "Just so you know, it's not free.",
  "Keep that in mind.",
  "Word of advice...",
  "Word of advice — don't mention it to her.",
  "Word of advice — always read the fine print.",
  "Word of advice — save your receipts.",
  "Word of advice — don't burn bridges.",
  "Word of advice — take it slow at first."
];

// Giving Up and Accepting
const giving_up_accepting_phrases = [
  "It is what it is.",
  "There's nothing I can do.",
  "That ship has sailed.",
  "What's done is done.",
  "No use crying over spilt milk.",
  "I've come to terms with it.",
  "I'll just have to deal with it.",
  "Oh well.",
  "Such is life.",
  "You win some, you lose some.",
  "That's life.",
  "I've given up trying.",
  "There's no getting around it.",
  "I guess that's just how it is.",
  "I've accepted it."
];

// Time Pressure and Urgency
const time_pressure_urgency_phrases = [
  "We're running out of time.",
  "We need to hurry.",
  "We're cutting it close.",
  "Time's up.",
  "We don't have much time.",
  "The clock is ticking.",
  "Let's not waste any more time.",
  "Hurry up!",
  "Come on, let's go!",
  "We're going to be late.",
  "We should get a move on.",
  "Chop chop!",
  "There's no time to lose.",
  "Let's pick up the pace.",
  "We need to crack on."
];

// Changing Your Mind
const changing_mind_phrases = [
  "On second thought...",
  "On second thought, let's just stay in.",
  "On second thought, maybe I should wait.",
  "On second thought, I'll have the soup instead.",
  "On second thought, you might be right.",
  "On second thought, I'd rather not.",
  "Actually, never mind.",
  "I take that back.",
  "Forget what I said.",
  "I've had a change of heart.",
  "I spoke too soon.",
  "You know what, forget it.",
  "I changed my mind.",
  "Scratch that.",
  "Scratch that — let's do it your way instead.",
  "Scratch that — I just remembered something.",
  "Scratch that — I think the first idea was better.",
  "Scratch that — she already confirmed.",
  "Scratch that — it's too late now."
];

// Setting Boundaries
const setting_boundaries_phrases = [
  "I'm going to have to say no.",
  "I appreciate the offer, but I can't.",
  "I'm not comfortable with that.",
  "I'd prefer not to.",
  "That's not something I'm willing to do.",
  "I need some space.",
  "I need some time to think.",
  "Let's not go there.",
  "I don't want to get involved.",
  "With all due respect, that's none of your business.",
  "I'd rather keep that private.",
  "I think we need to set some boundaries.",
  "That's where I draw the line.",
  "I'm putting my foot down.",
  "I've made my decision and it's final."
];

// Making Excuses and Justifying
const excuses_justifying_phrases = [
  "I didn't have a choice.",
  "I had no other option.",
  "It wasn't my fault.",
  "I couldn't help it.",
  "In my defence...",
  "In my defence, nobody told me.",
  "In my defence, I was half asleep.",
  "In my defence, the instructions weren't clear.",
  "In my defence, I'd never done this before.",
  "In my defence, I was under a lot of pressure.",
  "To be fair...",
  "To be fair, it was a difficult situation.",
  "To be fair, she didn't give us much notice.",
  "To be fair, he did try his best.",
  "To be fair, it's not as bad as it sounds.",
  "To be fair, we all make mistakes.",
  "I was running late because...",
  "I was running late because of the traffic.",
  "I was running late because my alarm didn't go off.",
  "I was running late because I couldn't find my keys.",
  "I was running late because the train was delayed.",
  "I was running late because I had to drop the kids off.",
  "I lost track of time.",
  "I got held up.",
  "Something unexpected happened.",
  "It's a long story."
];

// Expressing Doubt
const expressing_doubt_phrases = [
  "I'm not convinced.",
  "I have my doubts.",
  "I'm sceptical.",
  "I find that hard to believe.",
  "I'm not buying it.",
  "That doesn't add up.",
  "Something doesn't feel right.",
  "I don't think that's entirely true.",
  "Are you sure about that?",
  "I wouldn't be so sure.",
  "That sounds too good to be true.",
  "I'll believe it when I see it.",
  "I'm not so sure...",
  "I'm not so sure that's a good idea.",
  "I'm not so sure he's telling the truth.",
  "I'm not so sure we should trust them.",
  "I'm not so sure it'll work.",
  "I'm not so sure about this plan."
];

// Asking for Opinions
const asking_opinions_phrases = [
  "What do you reckon?",
  "What are your thoughts?",
  "What's your honest opinion?",
  "What would you suggest?",
  "What would you recommend?",
  "If you were in my shoes...",
  "If you were in my shoes, what would you do?",
  "If you were in my shoes, would you take the job?",
  "If you were in my shoes, how would you handle it?",
  "If you were in my shoes, would you say something?",
  "If you were in my shoes, would you wait or act now?",
  "Am I overthinking this?",
  "Am I being unreasonable?",
  "Does that sound fair?",
  "Do you think I'm wrong?"
];

// Hedging Opinions (Softening what you say)
const hedging_opinions_phrases = [
  "I could be wrong, but...",
  "I could be wrong, but I think she's upset.",
  "I could be wrong, but this looks familiar.",
  "I could be wrong, but I think we've missed something.",
  "I could be wrong, but that doesn't seem right.",
  "I could be wrong, but he might already know.",
  "It seems to me that...",
  "It seems to me that we need a new plan.",
  "It seems to me that she's not happy.",
  "It seems to me that there's been a misunderstanding.",
  "It seems to me that we're going in circles.",
  "It seems to me that the problem is communication.",
  "If you ask me...",
  "If you ask me, it's a waste of time.",
  "If you ask me, he should've known better.",
  "If you ask me, we should wait.",
  "If you ask me, the whole thing is overrated.",
  "If you ask me, she deserves the promotion.",
  "I might be wrong, but...",
  "I might be wrong, but I think it's the other way around.",
  "I might be wrong, but that doesn't match what he said.",
  "I might be wrong, but I think this has happened before.",
  "I might be wrong, but she seemed annoyed.",
  "I might be wrong, but I'd say it's worth trying."
];

// Reported Thoughts and Inner Monologue
const reported_thoughts_phrases = [
  "I thought to myself...",
  "I thought to myself, this can't be right.",
  "I thought to myself, maybe I should say something.",
  "I thought to myself, this is too good to be true.",
  "I thought to myself, I've been here before.",
  "I thought to myself, what's the worst that could happen?",
  "I was thinking...",
  "I was thinking we could go tomorrow instead.",
  "I was thinking about what you said earlier.",
  "I was thinking maybe we should try a different approach.",
  "I was thinking of taking a few days off.",
  "I was thinking it might be a good idea to wait.",
  "It occurred to me that...",
  "It occurred to me that we never replied.",
  "It occurred to me that she might be right.",
  "It occurred to me that we've been doing this wrong.",
  "It occurred to me that nobody asked permission.",
  "It occurred to me that there might be a simpler way.",
  "It crossed my mind that...",
  "It crossed my mind that he might not come.",
  "It crossed my mind that we should double-check.",
  "It crossed my mind that perhaps we're overthinking it.",
  "It crossed my mind that she might have forgotten.",
  "It crossed my mind that this could backfire."
];

// Ability in Different Tenses
const ability_tenses_phrases = [
  "I can do it.",
  "I can't do it.",
  "I could do it when I was younger.",
  "I couldn't do it at the time.",
  "I was able to finish it.",
  "I wasn't able to make it.",
  "I've been able to...",
  "I've been able to manage so far.",
  "I've been able to keep up with the work.",
  "I've been able to save a bit of money.",
  "I've been able to improve my English.",
  "I've been able to handle the pressure.",
  "I haven't been able to...",
  "I haven't been able to sleep properly.",
  "I haven't been able to reach her.",
  "I haven't been able to find a solution.",
  "I haven't been able to concentrate.",
  "I haven't been able to finish the report.",
  "I'll be able to help you tomorrow.",
  "I won't be able to make it.",
  "I should be able to...",
  "I should be able to finish by Friday.",
  "I should be able to get there on time.",
  "I should be able to sort it out.",
  "I should be able to find it online.",
  "I should be able to cover for you."
];

// Conditionals in Conversation (Mixed)
const conditionals_conversation_phrases = [
  "If you need anything, just let me know.",
  "If you change your mind, give me a ring.",
  "If I had more time, I'd help.",
  "If it were up to me, I'd say yes.",
  "If things had gone differently...",
  "If things had gone differently, I'd still be there.",
  "If things had gone differently, we wouldn't be here.",
  "If things had gone differently, she'd still have her job.",
  "If things had gone differently, I might have stayed.",
  "If things had gone differently, none of this would've happened.",
  "If I had known...",
  "If I had known, I would've come earlier.",
  "If I had known, I wouldn't have said that.",
  "If I had known, I'd have brought an umbrella.",
  "If I had known, I would've prepared something.",
  "If I had known, I never would've agreed.",
  "Unless something comes up, I'll be there.",
  "As long as you're happy, I'm happy.",
  "Provided that everything goes well, we should finish on time.",
  "Even if he apologises, I'm not changing my mind."
];

// Describing Habits with Used to and Would
const habits_past_phrases = [
  "I used to...",
  "I used to go running every morning.",
  "I used to live with my parents.",
  "I used to be really shy.",
  "I used to drink a lot of coffee.",
  "I used to hate cooking.",
  "We used to...",
  "We used to hang out every weekend.",
  "We used to go to the same school.",
  "We used to argue all the time.",
  "We used to live next door to each other.",
  "We used to play football after work.",
  "He would always...",
  "He would always bring flowers on Fridays.",
  "He would always crack jokes during meetings.",
  "He would always be the last one to leave.",
  "He would always check in on everyone.",
  "He would always forget his keys.",
  "She would never...",
  "She would never complain about anything.",
  "She would never miss a deadline.",
  "She would never say no to a challenge.",
  "She would never forget a birthday.",
  "She would never let anyone down."
];

// Describing Ongoing Situations (Present Perfect Continuous)
const ongoing_situations_phrases = [
  "I've been working here for three years.",
  "I've been trying to reach you all day.",
  "I've been feeling a bit under the weather.",
  "I've been learning English for two years.",
  "I've been thinking about changing jobs.",
  "She's been acting strange lately.",
  "He's been working really hard.",
  "They've been arguing a lot recently.",
  "It's been raining all morning.",
  "We've been waiting for ages.",
  "How long have you been working on this?",
  "How long have you been living here?",
  "How long has she been gone?",
  "How long has it been raining?",
  "How long have they been together?"
];

// Describing Changes
const describing_changes_phrases = [
  "Things have changed a lot.",
  "It's not like it used to be.",
  "It's gotten worse.",
  "It's gotten better.",
  "It's improving.",
  "It's getting more expensive.",
  "It's not what it used to be.",
  "Things are starting to...",
  "Things are starting to pick up.",
  "Things are starting to make sense.",
  "Things are starting to fall into place.",
  "Things are starting to go wrong.",
  "Things are starting to improve.",
  "It went from bad to worse.",
  "It's a whole different story now.",
  "It's come a long way.",
  "It's not the same anymore."
];

// Expressing Preferences in Context
const preferences_in_context_phrases = [
  "I'd much rather...",
  "I'd much rather stay in tonight.",
  "I'd much rather take the train.",
  "I'd much rather do it myself.",
  "I'd much rather talk in person.",
  "I'd much rather wait and see.",
  "I'm more of a...",
  "I'm more of a morning person.",
  "I'm more of a tea person.",
  "I'm more of a homebody.",
  "I'm more of a listener than a talker.",
  "I'm more of a dog person.",
  "I'm not really into...",
  "I'm not really into football.",
  "I'm not really into social media.",
  "I'm not really into horror films.",
  "I'm not really into going out late.",
  "I'm not really into cooking."
];

// Making Comparisons in Conversation
const making_comparisons_phrases = [
  "It's nothing like...",
  "It's nothing like what I expected.",
  "It's nothing like the old one.",
  "It's nothing like working in an office.",
  "It's nothing like the photos.",
  "It's nothing like living abroad.",
  "It's a lot like...",
  "It's a lot like driving — you just need practice.",
  "It's a lot like cooking — once you get the hang of it, it's easy.",
  "It's a lot like learning a language — consistency is key.",
  "It's a lot like what happened last time.",
  "It's a lot like his old job, actually.",
  "It's the same as...",
  "It's the same as last time.",
  "It's the same as what she said.",
  "It's the same as everywhere else.",
  "It's the same as the one we had before.",
  "It's the same as usual.",
  "It's way more... than...",
  "It's way more expensive than I thought.",
  "It's way more complicated than it looks.",
  "It's way more fun than I expected.",
  "It's way more work than they told me.",
  "It's way more stressful than my old job.",
  "Compared to...",
  "Compared to last year, things are better.",
  "Compared to her, I'm a beginner.",
  "Compared to the original, this is awful.",
  "Compared to working from home, commuting is exhausting.",
  "Compared to what we paid, it's a bargain."
];

// Softening Bad News
const softening_bad_news_phrases = [
  "I'm afraid...",
  "I'm afraid we didn't get it.",
  "I'm afraid that's not possible.",
  "I'm afraid she's already left.",
  "I'm afraid the results aren't great.",
  "I'm afraid there's been a complication.",
  "Unfortunately...",
  "Unfortunately, we have to cancel.",
  "Unfortunately, they said no.",
  "Unfortunately, it's out of our hands.",
  "Unfortunately, the position's been filled.",
  "Unfortunately, it's going to take longer than expected.",
  "I don't know how to tell you this, but...",
  "I don't know how to tell you this, but we lost the contract.",
  "I don't know how to tell you this, but she's leaving.",
  "I don't know how to tell you this, but the project's been cancelled.",
  "I don't know how to tell you this, but your flight's been delayed.",
  "I don't know how to tell you this, but he's not coming back.",
  "I hate to break it to you, but...",
  "I hate to break it to you, but you didn't pass.",
  "I hate to break it to you, but it's been sold.",
  "I hate to break it to you, but she wasn't impressed.",
  "I hate to break it to you, but we're over budget.",
  "I hate to break it to you, but they chose someone else."
];

// Emphasising a Point
const emphasising_point_phrases = [
  "The thing you have to understand is...",
  "The thing you have to understand is, this isn't easy.",
  "The thing you have to understand is, she's under a lot of pressure.",
  "The thing you have to understand is, it takes time.",
  "The thing you have to understand is, we've already tried that.",
  "The thing you have to understand is, there's no quick fix.",
  "What I'm getting at is...",
  "What I'm getting at is, we can't keep doing this.",
  "What I'm getting at is, something needs to change.",
  "What I'm getting at is, it's not sustainable.",
  "What I'm getting at is, we need to be honest.",
  "What I'm getting at is, this is bigger than we thought.",
  "My point is...",
  "My point is, it doesn't matter who's right.",
  "My point is, we wasted an opportunity.",
  "My point is, she tried her best.",
  "My point is, we need to move forward.",
  "My point is, let's not repeat the same mistake.",
  "What matters is...",
  "What matters is that you're safe.",
  "What matters is that we tried.",
  "What matters is the outcome.",
  "What matters is how we respond.",
  "What matters is that we stick together."
];

// Introducing a Story or Anecdote
const introducing_story_phrases = [
  "You won't believe what happened.",
  "So, listen to this...",
  "So, listen to this — I was at the shop yesterday...",
  "So, listen to this — she called me out of the blue...",
  "So, listen to this — I got there and the place was empty...",
  "So, listen to this — he walks in and just sits down...",
  "So, listen to this — they offered me the job on the spot...",
  "You know what happened to me the other day?",
  "This is going to sound crazy, but...",
  "This is going to sound crazy, but I saw him there.",
  "This is going to sound crazy, but she said yes.",
  "This is going to sound crazy, but they gave it to me for free.",
  "This is going to sound crazy, but I actually enjoyed it.",
  "This is going to sound crazy, but I dreamt about this exact thing.",
  "Let me tell you what happened.",
  "You're never going to believe this.",
  "Get this — ...",
  "Get this — he didn't even apologise.",
  "Get this — she already knew the whole time.",
  "Get this — they cancelled it an hour before.",
  "Get this — I ran into her at the airport.",
  "Get this — the same thing happened to me last week.",
  "So there I was...",
  "So there I was, standing in the rain...",
  "So there I was, waiting for the bus...",
  "So there I was, sitting in the meeting...",
  "So there I was, trying to act normal...",
  "So there I was, thinking everything was fine..."
];

// Summarising and Wrapping Up
const summarising_wrapping_up_phrases = [
  "So basically...",
  "So basically, we need to start over.",
  "So basically, it's not going to work.",
  "So basically, she said no.",
  "So basically, we're back to square one.",
  "So basically, everything went wrong.",
  "To sum it up...",
  "To sum it up, it was a disaster.",
  "To sum it up, we learned a lot.",
  "To sum it up, it went better than expected.",
  "To sum it up, nobody was happy.",
  "To sum it up, we made the right call.",
  "All in all...",
  "All in all, it was a good experience.",
  "All in all, I'd say it went well.",
  "All in all, we can't complain.",
  "All in all, it wasn't worth it.",
  "All in all, I'm glad we did it.",
  "The point is...",
  "The point is, we need to act now.",
  "The point is, it doesn't matter who started it.",
  "The point is, she's not coming back.",
  "The point is, we can't afford to wait.",
  "The point is, we all need to be on the same page.",
  "What I'm trying to say is...",
  "What I'm trying to say is, I think we should stop.",
  "What I'm trying to say is, it's not personal.",
  "What I'm trying to say is, I care about this.",
  "What I'm trying to say is, we need a different approach.",
  "What I'm trying to say is, you deserve better."
];

// Showing Agreement Strongly
const strong_agreement_phrases = [
  "Spot on.",
  "You hit the nail on the head.",
  "That's exactly what I was thinking.",
  "My thoughts exactly.",
  "You took the words right out of my mouth.",
  "I was just about to say that.",
  "Tell me about it.",
  "You're not wrong.",
  "A hundred percent.",
  "I second that."
];

// Showing Interest and Active Listening
const showing_interest_phrases = [
  "Oh really? That's interesting.",
  "Wow, I didn't know that.",
  "That's fascinating.",
  "I'd love to hear more about that.",
  "How so?",
  "What do you mean by that?",
  "In what way?",
  "That's a new one.",
  "I've never thought about it that way.",
  "That's a really good point.",
  "Makes sense.",
  "Right, right.",
  "Yeah, exactly.",
  "Oh, I see what you mean.",
  "Fair point."
];

// Checking on Someone
const checking_on_someone_phrases = [
  "Are you alright?",
  "You okay?",
  "Everything alright?",
  "Is everything okay?",
  "What's the matter?",
  "What happened?",
  "You seem a bit off today.",
  "You don't look too well.",
  "Is there anything I can do?",
  "Do you want to talk about it?",
  "Let me know if you need anything.",
  "I'm here if you need me.",
  "Take your time.",
  "There's no rush.",
  "Don't push yourself."
];

// Making Small Talk About Weather
const weather_small_talk_phrases = [
  "Lovely day, isn't it?",
  "Awful weather, isn't it?",
  "Can you believe this rain?",
  "It's absolutely freezing.",
  "It's boiling out there.",
  "Looks like it might rain.",
  "At least the sun's out.",
  "I hope the weather holds up.",
  "It's meant to be nice this weekend.",
  "I'm so sick of this weather."
];

// Correcting Yourself
const correcting_yourself_phrases = [
  "Sorry, what I meant was...",
  "Sorry, what I meant was, we should meet on Tuesday, not Monday.",
  "Sorry, what I meant was, I agree with the second option.",
  "Sorry, what I meant was, it's not urgent.",
  "Sorry, what I meant was, she's the project lead.",
  "Sorry, what I meant was, it's the other building.",
  "Let me rephrase that.",
  "That came out wrong.",
  "That's not what I meant.",
  "What I'm trying to say is...",
  "What I'm trying to say is, I appreciate it.",
  "What I'm trying to say is, it's complicated.",
  "What I'm trying to say is, I need more time.",
  "What I'm trying to say is, I'm not ready.",
  "What I'm trying to say is, I disagree but I respect your opinion."
];

// Conversation Closers (Before goodbye)
const conversation_closers_phrases = [
  "Well, it's been lovely chatting.",
  "Right, I'd better get going.",
  "I should probably head off.",
  "I won't take up any more of your time.",
  "It was really nice catching up.",
  "Let's do this again soon.",
  "We should definitely do this more often.",
  "I'll let you get back to it.",
  "I'd better let you go.",
  "Give me a shout if you need anything.",
  "Keep in touch.",
  "Don't be a stranger.",
  "Say hi to everyone for me.",
  "Send my regards.",
  "Look after yourself."
];

// Expressing Ability and Inability
const expressing_ability_inability_phrases = [
  "I can handle it.",
  "I can manage.",
  "I can't cope.",
  "I can't keep up.",
  "I can barely hear you.",
  "I can barely keep my eyes open.",
  "I can't get my head around it.",
  "I can't make sense of it.",
  "I can't figure it out.",
  "I can't get it to work.",
  "I managed to...",
  "I managed to sort it out in the end.",
  "I managed to get there just in time.",
  "I managed to convince him.",
  "I managed to find a workaround.",
  "I managed to squeeze it in."
];

// Responding to Thank You
const responding_to_thanks_phrases = [
  "Don't mention it.",
  "Not at all.",
  "You're welcome.",
  "Anytime.",
  "My pleasure.",
  "Happy to help.",
  "It was nothing.",
  "No trouble at all.",
  "That's what I'm here for.",
  "Glad I could help."
];

// Responding to Apologies
const responding_to_apologies_phrases = [
  "No worries.",
  "It's fine, honestly.",
  "Don't worry about it.",
  "It's all good.",
  "Water under the bridge.",
  "No harm done.",
  "It happens.",
  "Forget about it.",
  "It's nothing.",
  "Apology accepted."
];